//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalInfo
    {
        public AdditionalInfo()
        {
            this.Requirement = new HashSet<Requirement>();
        }
    
        public short AdditionalInfoId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Requirement> Requirement { get; set; }
    }
}
