//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.ListingLocation = new HashSet<ListingLocation>();
            this.RequirementLocation = new HashSet<RequirementLocation>();
            this.VendorServiceLocation = new HashSet<VendorServiceLocation>();
        }
    
        public string AreaId { get; set; }
        public int CityId { get; set; }
        public string PlaceId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Pin { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<ListingLocation> ListingLocation { get; set; }
        public virtual ICollection<RequirementLocation> RequirementLocation { get; set; }
        public virtual ICollection<VendorServiceLocation> VendorServiceLocation { get; set; }
    }
}
