//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryRelation
    {
        public int CategoryRelationId { get; set; }
        public int ParentCategoryId { get; set; }
        public int ChildCategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Category Category1 { get; set; }
    }
}
