//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.CategoryRelation = new HashSet<CategoryRelation>();
            this.CategoryRelation1 = new HashSet<CategoryRelation>();
            this.RequirementCategory = new HashSet<RequirementCategory>();
            this.ListingCategory = new HashSet<ListingCategory>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Popularity { get; set; }
    
        public virtual ICollection<CategoryRelation> CategoryRelation { get; set; }
        public virtual ICollection<CategoryRelation> CategoryRelation1 { get; set; }
        public virtual ICollection<RequirementCategory> RequirementCategory { get; set; }
        public virtual ICollection<ListingCategory> ListingCategory { get; set; }
    }
}
