//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Area = new HashSet<Area>();
            this.ListingLocation = new HashSet<ListingLocation>();
            this.RequirementLocation = new HashSet<RequirementLocation>();
            this.VendorServiceLocation = new HashSet<VendorServiceLocation>();
        }
    
        public int CityId { get; set; }
        public string Name { get; set; }
        public int StateId { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public bool IsPopular { get; set; }
        public short PopulationClass { get; set; }
    
        public virtual ICollection<Area> Area { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<ListingLocation> ListingLocation { get; set; }
        public virtual ICollection<RequirementLocation> RequirementLocation { get; set; }
        public virtual ICollection<VendorServiceLocation> VendorServiceLocation { get; set; }
    }
}
