//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.State = new HashSet<State>();
        }
    
        public short CountryId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Currency { get; set; }
        public string ISD { get; set; }
    
        public virtual ICollection<State> State { get; set; }
    }
}
