//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.ListingMedia = new HashSet<ListingMedia>();
        }
    
        public long FileId { get; set; }
        public short FileExtensionId { get; set; }
        public short FileTypeId { get; set; }
        public string FileTitle { get; set; }
        public string Description { get; set; }
        public string OriginalFileName { get; set; }
        public string ServerFileName { get; set; }
        public string ServerPath { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual FileExtension FileExtension { get; set; }
        public virtual FileType FileType { get; set; }
        public virtual ICollection<ListingMedia> ListingMedia { get; set; }
    }
}
