//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        public Requirement()
        {
            this.RequirementCategory = new HashSet<RequirementCategory>();
            this.RequirementLocation = new HashSet<RequirementLocation>();
        }
    
        public long RequirementId { get; set; }
        public long UserId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> LikeCount { get; set; }
        public Nullable<int> DislikeCount { get; set; }
        public Nullable<int> AbuseCount { get; set; }
        public Nullable<short> LevelId { get; set; }
        public Nullable<short> AdditionalInfoId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AdditionalInfo AdditionalInfo { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<RequirementCategory> RequirementCategory { get; set; }
        public virtual ICollection<RequirementLocation> RequirementLocation { get; set; }
    }
}
