//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TMCContext : DbContext
    {
        public TMCContext()
            : base("name=TMCContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<AdditionalInfo> AdditionalInfo { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryRelation> CategoryRelation { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<ContactType> ContactType { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<File> File { get; set; }
        public virtual DbSet<FileExtension> FileExtension { get; set; }
        public virtual DbSet<FileType> FileType { get; set; }
        public virtual DbSet<Listing> Listing { get; set; }
        public virtual DbSet<ListingContact> ListingContact { get; set; }
        public virtual DbSet<ListingLocation> ListingLocation { get; set; }
        public virtual DbSet<ListingMedia> ListingMedia { get; set; }
        public virtual DbSet<ListingPaymentMode> ListingPaymentMode { get; set; }
        public virtual DbSet<PaymentMode> PaymentMode { get; set; }
        public virtual DbSet<Requirement> Requirement { get; set; }
        public virtual DbSet<RequirementCategory> RequirementCategory { get; set; }
        public virtual DbSet<RequirementLocation> RequirementLocation { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
        public virtual DbSet<VendorServiceLocation> VendorServiceLocation { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<ListingCategory> ListingCategory { get; set; }
    }
}
