//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorServiceLocation
    {
        public long VendorServiceLocationId { get; set; }
        public long VendorId { get; set; }
        public Nullable<bool> IsGlobalLevel { get; set; }
        public Nullable<bool> IsCountryLevel { get; set; }
        public Nullable<bool> IsStateLevel { get; set; }
        public Nullable<bool> IsCityLevel { get; set; }
        public Nullable<int> CityId { get; set; }
        public string AreaId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual City City { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
